#!/usr/bin/env ansible-playbook
---
- name: Clone instance
  hosts: pve_server
  roles:
    - role: ../../roles/clone_template
    - { role: ../../roles/lxc_post_config, when: (temporary == "no") }

- name: Update instance
  hosts: "{{ (temporary == 'no') | ternary(hostvars['pve_server']['static_instance_ip'], hostvars['pve_server']['instance_ip']) }}"
  vars_files: ../../vars.yml
  tasks:
    - name: Perform system upgrade
      community.general.apt_rpm:
        update_cache: true
        dist_upgrade: true

    - name: Reboot system
      ansible.builtin.reboot:
        connect_timeout: 10
        reboot_timeout: 60

    - name: Install docker packages
      community.general.apt_rpm:
        name:
          - docker-engine
          - docker-compose-v2
      when: for_docker == "yes"

    - name: Configure docker daemon.json
      ansible.builtin.lineinfile:
        path: /etc/docker/daemon.json
        line: '"hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"],'
        insertafter: '^\s*\{\s*$'
        firstmatch: true
        state: present
        create: no
      when: for_docker == "yes"

    - name: Start docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      when: for_docker == "yes"
