#!/usr/bin/env ansible-playbook
---
- name: Clone template
  hosts: pve_server
  vars:
    new_hostname: traefik
  roles:
    - role: ../../roles/clone_template
    - role: ../../roles/lxc_post_config

- name: Configure traefik
  hosts: "{{ hostvars['pve_server']['static_instance_ip'] }}"
  tasks:
    - name: Include common variables
      ansible.builtin.include_vars:
        file: ../../vars.yml

    - name: Perform system upgrade
      community.general.apt_rpm:
        update_cache: true
        dist_upgrade: true

    - name: Install traefik
      community.general.apt_rpm:
        name:
          - traefik
        state: present

    - name: Configure traefik
      ansible.builtin.template:
        src: traefik.toml.j2
        dest: /etc/traefik/traefik.toml

    - name: Configure traefik dashboard
      ansible.builtin.template:
        src: dashboard.yml.j2
        dest: /etc/traefik/traefik.d/dashboard.yml

    - name: Start traefik service
      ansible.builtin.systemd:
        name: traefik
        state: started
        enabled: yes
