#!/usr/bin/env ansible-playbook
---
- name: Clone template
  hosts: pve_server
  vars:
    new_hostname: traefik
  roles:
    - role: ../../roles/clone_template
  tasks:
    - name: Enable onboot start
      community.general.proxmox:
        api_host: "{{ pve_node_name }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ pve_node_name }}"
        vmid: "{{ new_vm_id }}"
        hostname: "{{ new_hostname }}"
        onboot: true
        update: true

- name: Configure traefik
  hosts: "{{ hostvars['pve_server']['instance_ip'] }}"
  tasks:
    - name: Include common variables
      ansible.builtin.include_vars:
        file: ../../vars.yml

    - name: Perform system upgrade
      community.general.apt_rpm:
        update_cache: true
        dist_upgrade: true

    - name: Install traefik
      community.general.apt_rpm:
        name:
          - traefik
        state: present

    - name: Configure traefik
      ansible.builtin.template:
        src: traefik.toml.j2
        dest: /etc/traefik/traefik.toml

    - name: Configure traefik dashboard
      ansible.builtin.template:
        src: dashboard.yml.j2
        dest: /etc/traefik/traefik.d/dashboard.yml

    - name: Start traefik service
      ansible.builtin.systemd:
        name: traefik
        state: started
        enabled: yes
